# Server Configuration
server.port=9000

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/loan_disbursement
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop

# JWT Configuration
jwt.secret=B374A26A71490437AA024E4F275A6D275A6D275A6D275A6D275A6D275A6D275A6D275A6D275A6D275A6D
jwt.expiration=86400000