# Server Configuration
server.port=9000

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/loan_disbursement
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA Configuration
# Set to 'none' to prevent Hibernate from automatically altering the schema.
# This will preserve your data across application restarts.
# You will need to manage schema changes manually via SQL scripts.
spring.jpa.hibernate.ddl-auto=none

# JWT Configuration
jwt.secret=B374A26A71490437AA024E4F275A6D275A6D275A6D275A6D275A6D275A6D275A6D275A6D275A6D275A6D
jwt.expiration=300000
